// <auto-generated />
using System;
using Exa_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exa_2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221115141050_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exa_2.Data.Entity.Floors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Indoor_plants")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActivate")
                        .HasColumnType("bit");

                    b.Property<bool>("Medicinal_plants")
                        .HasColumnType("bit");

                    b.Property<string>("Plant_Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Plant_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Plant_Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Plant_cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Plant_family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Plant_sold")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Plant_years")
                        .HasMaxLength(8)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Planting_amount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Planting_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("floors");
                });

            modelBuilder.Entity("Exa_2.Data.Entity.Irrigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActivate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Plantation_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plantation_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plantation_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plantation_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Planting_amount")
                        .HasColumnType("float");

                    b.Property<string>("Type_land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Watering_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("irrigations");
                });
#pragma warning restore 612, 618
        }
    }
}
